const enum Gaps {
	StartX=20,
	StartY=274,
	KeyX=12,
	FirstRow0=114,
	FirstRow4=86,
	FirstRow8=62,
	SixthRow0=196,
	SixthRow3=196,
	EditRowA=44,
	EditRowB=44,
	KeyY=8
}
const enum SizeX {
	Key=130,
	Double=Key*2+Gaps.KeyX,
	Backspace=214,
	Tab=190,
	Backslash=154,
	Caps=228,
	Enter=258,
	Shift=314,
	Ctrl=196,
	Alt=196,
	Space=860
}
const enum SizeY {
	Key=120,
	Double=Key*2+Gaps.KeyY,
}
const enum PosX { //All lined up nicely!
	FirstRow00=Gaps.StartX,
	FirstRow01=FirstRow00+SizeX.Key+Gaps.FirstRow0,
	FirstRow02=FirstRow01+SizeX.Key+Gaps.KeyX,
	FirstRow03=FirstRow02+SizeX.Key+Gaps.KeyX,
	FirstRow04=FirstRow03+SizeX.Key+Gaps.KeyX,
	FirstRow05=FirstRow04+SizeX.Key+Gaps.FirstRow4,
	FirstRow06=FirstRow05+SizeX.Key+Gaps.KeyX,
	FirstRow07=FirstRow06+SizeX.Key+Gaps.KeyX,
	FirstRow08=FirstRow07+SizeX.Key+Gaps.KeyX,
	FirstRow09=FirstRow08+SizeX.Key+Gaps.FirstRow8,
	FirstRow10=FirstRow09+SizeX.Key+Gaps.KeyX,
	FirstRow11=FirstRow10+SizeX.Key+Gaps.KeyX,
	FirstRow12=FirstRow11+SizeX.Key+Gaps.KeyX,
	SecondRow00=FirstRow00,
	SecondRow01=SecondRow00+SizeX.Key+Gaps.KeyX,
	SecondRow02=SecondRow01+SizeX.Key+Gaps.KeyX,
	SecondRow03=SecondRow02+SizeX.Key+Gaps.KeyX,
	SecondRow04=SecondRow03+SizeX.Key+Gaps.KeyX,
	SecondRow05=SecondRow04+SizeX.Key+Gaps.KeyX,
	SecondRow06=SecondRow05+SizeX.Key+Gaps.KeyX,
	SecondRow07=SecondRow06+SizeX.Key+Gaps.KeyX,
	SecondRow08=SecondRow07+SizeX.Key+Gaps.KeyX,
	SecondRow09=SecondRow08+SizeX.Key+Gaps.KeyX,
	SecondRow10=SecondRow09+SizeX.Key+Gaps.KeyX,
	SecondRow11=SecondRow10+SizeX.Key+Gaps.KeyX,
	SecondRow12=SecondRow11+SizeX.Key+Gaps.KeyX,
	SecondRow13=SecondRow12+SizeX.Key+Gaps.KeyX,
	ThirdRow00=SecondRow00,
	ThirdRow01=ThirdRow00+SizeX.Tab+Gaps.KeyX,
	ThirdRow02=ThirdRow01+SizeX.Key+Gaps.KeyX,
	ThirdRow03=ThirdRow02+SizeX.Key+Gaps.KeyX,
	ThirdRow04=ThirdRow03+SizeX.Key+Gaps.KeyX,
	ThirdRow05=ThirdRow04+SizeX.Key+Gaps.KeyX,
	ThirdRow06=ThirdRow05+SizeX.Key+Gaps.KeyX,
	ThirdRow07=ThirdRow06+SizeX.Key+Gaps.KeyX,
	ThirdRow08=ThirdRow07+SizeX.Key+Gaps.KeyX,
	ThirdRow09=ThirdRow08+SizeX.Key+Gaps.KeyX,
	ThirdRow10=ThirdRow09+SizeX.Key+Gaps.KeyX,
	ThirdRow11=ThirdRow10+SizeX.Key+Gaps.KeyX,
	ThirdRow12=ThirdRow11+SizeX.Key+Gaps.KeyX,
	ThirdRow13=ThirdRow12+SizeX.Key+Gaps.KeyX,
	FourthRow00=ThirdRow00,
	FourthRow01=FourthRow00+SizeX.Caps+Gaps.KeyX,
	FourthRow02=FourthRow01+SizeX.Key+Gaps.KeyX,
	FourthRow03=FourthRow02+SizeX.Key+Gaps.KeyX,
	FourthRow04=FourthRow03+SizeX.Key+Gaps.KeyX,
	FourthRow05=FourthRow04+SizeX.Key+Gaps.KeyX,
	FourthRow06=FourthRow05+SizeX.Key+Gaps.KeyX,
	FourthRow07=FourthRow06+SizeX.Key+Gaps.KeyX,
	FourthRow08=FourthRow07+SizeX.Key+Gaps.KeyX,
	FourthRow09=FourthRow08+SizeX.Key+Gaps.KeyX,
	FourthRow10=FourthRow09+SizeX.Key+Gaps.KeyX,
	FourthRow11=FourthRow10+SizeX.Key+Gaps.KeyX,
	FourthRow12=FourthRow11+SizeX.Key+Gaps.KeyX,
	FifthRow00=FourthRow00,
	FifthRow01=FifthRow00+SizeX.Shift+Gaps.KeyX,
	FifthRow02=FifthRow01+SizeX.Key+Gaps.KeyX,
	FifthRow03=FifthRow02+SizeX.Key+Gaps.KeyX,
	FifthRow04=FifthRow03+SizeX.Key+Gaps.KeyX,
	FifthRow05=FifthRow04+SizeX.Key+Gaps.KeyX,
	FifthRow06=FifthRow05+SizeX.Key+Gaps.KeyX,
	FifthRow07=FifthRow06+SizeX.Key+Gaps.KeyX,
	FifthRow08=FifthRow07+SizeX.Key+Gaps.KeyX,
	FifthRow09=FifthRow08+SizeX.Key+Gaps.KeyX,
	FifthRow10=FifthRow09+SizeX.Key+Gaps.KeyX,
	FifthRow11=FifthRow10+SizeX.Key+Gaps.KeyX,
	SixthRow0=FifthRow00,
	SixthRow1=SixthRow0+SizeX.Ctrl+Gaps.SixthRow0,
	SixthRow2=SixthRow1+SizeX.Alt+Gaps.KeyX,
	SixthRow3=SixthRow2+SizeX.Space+Gaps.KeyX,
	SixthRow4=SixthRow3+SizeX.Alt+Gaps.SixthRow3,
	EditRow0=((FirstRow12+SizeX.Key)+(SecondRow13+SizeX.Backspace)+(ThirdRow13+SizeX.Backslash)+(FourthRow12+SizeX.Enter)+(FifthRow11+SizeX.Shift)+(SixthRow4+SizeX.Ctrl))/6+Gaps.EditRowA,
	EditRow1=EditRow0+SizeX.Key+Gaps.KeyX,
	EditRow2=EditRow1+SizeX.Key+Gaps.KeyX,
	EditRow3=EditRow2+SizeX.Key+Gaps.EditRowB,
	EditRow4=EditRow3+SizeX.Key+Gaps.KeyX,
	EditRow5=EditRow4+SizeX.Key+Gaps.KeyX,
	EditRow6=EditRow5+SizeX.Key+Gaps.KeyX,
}
const enum PosY { //All lined up nicely!
	FirstRow=Gaps.StartY,
	SecondRow=FirstRow+SizeY.Key+Gaps.KeyY,
	ThirdRow=SecondRow+SizeY.Key+Gaps.KeyY,
	FourthRow=ThirdRow+SizeY.Key+Gaps.KeyY,
	FifthRow=FourthRow+SizeY.Key+Gaps.KeyY,
	SixthRow=FifthRow+SizeY.Key+Gaps.KeyY,
}
class Button {
	readonly name: string;
	readonly x: number;
	readonly y: number;
	readonly w: number;
	readonly h: number;
	actions: string[];
	drawkey(ctx: CanvasRenderingContext2D): void {
		ctx.strokeRect(this.x,this.y,this.w,this.h);
		ctx.font="bold 24px sans-serif";
		ctx.textAlign="right";
		ctx.fillText(this.name,this.x+this.w-4,this.y+24);
		ctx.textAlign="left";
		ctx.font="12px sans-serif";
		for(let i=0;i<this.actions.length;i++) {
			ctx.fillText(this.actions[i],this.x+4,this.y+this.h-4-(12*(this.actions.length-1-i)));
		}
	}
	constructor(name: string,x: number,y: number,w: number,h: number) {
		this.name=name;
		this.x=x;
		this.y=y;
		this.w=w;
		this.h=h;
		this.actions=[];
	}
};
type Keys={
	Key_Backspace?: Button,
	Key_Tab?: Button,
	Key_Enter?: Button,
	Key_Pause?: Button,
	Key_CapsLock?: Button,
	Key_Kana?: Button,
	Key_Kanji?: Button,
	Key_Escape?: Button,
	Key_Convert?: Button,
	Key_NoConvert?: Button,
	Key_Space?: Button,
	Key_PageUp?: Button,
	Key_PageDown?: Button,
	Key_End?: Button,
	Key_Home?: Button,
	Key_LeftArrow?: Button,
	Key_UpArrow?: Button,
	Key_RightArrow?: Button,
	Key_DownArrow?: Button,
	Key_SYSRQ?: Button,
	Key_Insert?: Button,
	Key_Delete?: Button,
	Key_0?: Button,
	Key_1?: Button,
	Key_2?: Button,
	Key_3?: Button,
	Key_4?: Button,
	Key_5?: Button,
	Key_6?: Button,
	Key_7?: Button,
	Key_8?: Button,
	Key_9?: Button,
	Key_A?: Button,
	Key_B?: Button,
	Key_C?: Button,
	Key_D?: Button,
	Key_E?: Button,
	Key_F?: Button,
	Key_G?: Button,
	Key_H?: Button,
	Key_I?: Button,
	Key_J?: Button,
	Key_K?: Button,
	Key_L?: Button,
	Key_M?: Button,
	Key_N?: Button,
	Key_O?: Button,
	Key_P?: Button,
	Key_Q?: Button,
	Key_R?: Button,
	Key_S?: Button,
	Key_T?: Button,
	Key_U?: Button,
	Key_V?: Button,
	Key_W?: Button,
	Key_X?: Button,
	Key_Y?: Button,
	Key_Z?: Button,
	Key_LeftWin?: Button,
	Key_RightWin?: Button,
	Key_Apps?: Button,
	Key_Sleep?: Button,
	Key_Numpad_0?: Button,
	Key_Numpad_1?: Button,
	Key_Numpad_2?: Button,
	Key_Numpad_3?: Button,
	Key_Numpad_4?: Button,
	Key_Numpad_5?: Button,
	Key_Numpad_6?: Button,
	Key_Numpad_7?: Button,
	Key_Numpad_8?: Button,
	Key_Numpad_9?: Button,
	Key_Numpad_Multiply?: Button,
	Key_Numpad_Add?: Button,
	Key_Numpad_Subtract?: Button,
	Key_Numpad_Decimal?: Button,
	Key_Numpad_Comma?: Button,
	Key_Numpad_Divide?: Button,
	Key_Numpad_Enter?: Button,
	Key_F1?: Button,
	Key_F2?: Button,
	Key_F3?: Button,
	Key_F4?: Button,
	Key_F5?: Button,
	Key_F6?: Button,
	Key_F7?: Button,
	Key_F8?: Button,
	Key_F9?: Button,
	Key_F10?: Button,
	Key_F11?: Button,
	Key_F12?: Button,
	Key_F13?: Button,
	Key_F14?: Button,
	Key_F15?: Button,
	Key_F16?: Button,
	Key_F17?: Button,
	Key_F18?: Button,
	Key_F19?: Button,
	Key_F20?: Button,
	Key_F21?: Button,
	Key_F22?: Button,
	Key_F23?: Button,
	Key_F24?: Button,
	Key_NumLock?: Button,
	Key_ScrollLock?: Button,
	Key_LeftShift?: Button,
	Key_RightShift?: Button,
	Key_LeftControl?: Button,
	Key_RightControl?: Button,
	Key_LeftAlt?: Button,
	Key_RightAlt?: Button,
	Key_WebBack?: Button,
	Key_WebForward?: Button,
	Key_WebRefresh?: Button,
	Key_WebStop?: Button,
	Key_WebSearch?: Button,
	Key_WebFavourites?: Button,
	Key_WebHome?: Button,
	Key_Mute?: Button,
	Key_VolumeDown?: Button,
	Key_VolumeUp?: Button,
	Key_NextTrack?: Button,
	Key_PrevTrack?: Button,
	Key_MediaStop?: Button,
	Key_Stop?: Button,
	Key_PlayPause?: Button,
	Key_Mail?: Button,
	Key_MediaSelect?: Button,
	Key_SemiColon?: Button,
	Key_Plus?: Button,
	Key_Equals?: Button,
	Key_Comma?: Button,
	Key_Minus?: Button,
	Key_Period?: Button,
	Key_Slash?: Button,
	Key_Grave?: Button,
	Key_LeftBracket?: Button,
	Key_BackSlash?: Button,
	Key_RightBracket?: Button,
	Key_Apostrophe?: Button,
	Key_OEM_102?: Button,
	Key_ä?: Button,
	Key_ö?: Button,
	Key_ü?: Button,
	Key_ß?: Button,
	Key_Acute?: Button,
	Key_LessThan?: Button,
	Key_Circumflex?: Button,
	Key_Hash?: Button,
	Key_Colon?: Button,
	Key_ABNT_C1?: Button,
	Key_Yen?: Button,
	Key_ABNT_C2?: Button,
	Key_Numpad_Equals?: Button,
	Key_Underline?: Button,
	Key_AX?: Button,
	Key_Unlabeled?: Button,
	Key_Calculator?: Button,
	Key_AT?: Button,
	Key_Power?: Button,
	Key_Wake?: Button,
	Key_MyComputer?: Button,
	Key_GreenModifier?: Button,
	Key_OrangeModifier?: Button;
};
const keyboard: Keys={
	Key_Backspace: new Button("Backspace",PosX.SecondRow13,PosY.SecondRow,SizeX.Backspace,SizeY.Key),
	Key_Tab: new Button("Tab",PosX.ThirdRow00,PosY.ThirdRow,SizeX.Tab,SizeY.Key),
	Key_Enter: new Button("Enter",PosX.FourthRow12,PosY.FourthRow,SizeX.Enter,SizeY.Key),
	// Key_Pause: new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	Key_CapsLock: new Button("Caps",PosX.FourthRow00,PosY.FourthRow,SizeX.Caps,SizeY.Key),
	// Key_Kana:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_Kanji:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	Key_Escape: new Button("Esc",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_Convert:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_NoConvert:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	Key_Space: new Button("Space",PosX.SixthRow2,PosY.SixthRow,SizeX.Space,SizeY.Key),
	Key_PageUp: new Button("PgUp",PosX.EditRow2,PosY.SecondRow,SizeX.Key,SizeY.Key),
	Key_PageDown: new Button("PgDown",PosX.EditRow2,PosY.ThirdRow,SizeX.Key,SizeY.Key),
	Key_End: new Button("End",PosX.EditRow1,PosY.ThirdRow,SizeX.Key,SizeY.Key),
	Key_Home: new Button("Home",PosX.EditRow1,PosY.SecondRow,SizeX.Key,SizeY.Key),
	Key_LeftArrow: new Button("Left",PosX.EditRow0,PosY.SixthRow,SizeX.Key,SizeY.Key),
	Key_UpArrow: new Button("Up",PosX.EditRow1,PosY.FifthRow,SizeX.Key,SizeY.Key),
	Key_RightArrow: new Button("Right",PosX.EditRow2,PosY.SixthRow,SizeX.Key,SizeY.Key),
	Key_DownArrow: new Button("Down",PosX.EditRow1,PosY.SixthRow,SizeX.Key,SizeY.Key),
	// Key_SYSRQ:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	Key_Insert: new Button("Insert",PosX.EditRow0,PosY.SecondRow,SizeX.Key,SizeY.Key),
	Key_Delete: new Button("Delete",PosX.EditRow0,PosY.ThirdRow,SizeX.Key,SizeY.Key),
	Key_0: new Button("0",PosX.SecondRow10,PosY.SecondRow,SizeX.Key,SizeY.Key),
	Key_1: new Button("1",PosX.SecondRow01,PosY.SecondRow,SizeX.Key,SizeY.Key),
	Key_2: new Button("2",PosX.SecondRow02,PosY.SecondRow,SizeX.Key,SizeY.Key),
	Key_3: new Button("3",PosX.SecondRow03,PosY.SecondRow,SizeX.Key,SizeY.Key),
	Key_4: new Button("4",PosX.SecondRow04,PosY.SecondRow,SizeX.Key,SizeY.Key),
	Key_5: new Button("5",PosX.SecondRow05,PosY.SecondRow,SizeX.Key,SizeY.Key),
	Key_6: new Button("6",PosX.SecondRow06,PosY.SecondRow,SizeX.Key,SizeY.Key),
	Key_7: new Button("7",PosX.SecondRow07,PosY.SecondRow,SizeX.Key,SizeY.Key),
	Key_8: new Button("8",PosX.SecondRow08,PosY.SecondRow,SizeX.Key,SizeY.Key),
	Key_9: new Button("9",PosX.SecondRow09,PosY.SecondRow,SizeX.Key,SizeY.Key),
	Key_A: new Button("A",PosX.FourthRow01,PosY.FourthRow,SizeX.Key,SizeY.Key),
	Key_B: new Button("B",PosX.FifthRow05,PosY.FifthRow,SizeX.Key,SizeY.Key),
	Key_C: new Button("C",PosX.FifthRow03,PosY.FifthRow,SizeX.Key,SizeY.Key),
	Key_D: new Button("D",PosX.FourthRow03,PosY.FourthRow,SizeX.Key,SizeY.Key),
	Key_E: new Button("E",PosX.ThirdRow03,PosY.ThirdRow,SizeX.Key,SizeY.Key),
	Key_F: new Button("F",PosX.FourthRow04,PosY.FourthRow,SizeX.Key,SizeY.Key),
	Key_G: new Button("G",PosX.FourthRow05,PosY.FourthRow,SizeX.Key,SizeY.Key),
	Key_H: new Button("H",PosX.FourthRow06,PosY.FourthRow,SizeX.Key,SizeY.Key),
	Key_I: new Button("I",PosX.ThirdRow08,PosY.ThirdRow,SizeX.Key,SizeY.Key),
	Key_J: new Button("J",PosX.FourthRow07,PosY.FourthRow,SizeX.Key,SizeY.Key),
	Key_K: new Button("K",PosX.FourthRow08,PosY.FourthRow,SizeX.Key,SizeY.Key),
	Key_L: new Button("L",PosX.FourthRow09,PosY.FourthRow,SizeX.Key,SizeY.Key),
	Key_M: new Button("M",PosX.FifthRow07,PosY.FifthRow,SizeX.Key,SizeY.Key),
	Key_N: new Button("N",PosX.FifthRow06,PosY.FifthRow,SizeX.Key,SizeY.Key),
	Key_O: new Button("O",PosX.ThirdRow09,PosY.ThirdRow,SizeX.Key,SizeY.Key),
	Key_P: new Button("P",PosX.ThirdRow10,PosY.ThirdRow,SizeX.Key,SizeY.Key),
	Key_Q: new Button("Q",PosX.ThirdRow01,PosY.ThirdRow,SizeX.Key,SizeY.Key),
	Key_R: new Button("R",PosX.ThirdRow04,PosY.ThirdRow,SizeX.Key,SizeY.Key),
	Key_S: new Button("S",PosX.FourthRow02,PosY.FourthRow,SizeX.Key,SizeY.Key),
	Key_T: new Button("T",PosX.ThirdRow05,PosY.ThirdRow,SizeX.Key,SizeY.Key),
	Key_U: new Button("U",PosX.ThirdRow07,PosY.ThirdRow,SizeX.Key,SizeY.Key),
	Key_V: new Button("V",PosX.FifthRow04,PosY.FifthRow,SizeX.Key,SizeY.Key),
	Key_W: new Button("W",PosX.ThirdRow02,PosY.ThirdRow,SizeX.Key,SizeY.Key),
	Key_X: new Button("X",PosX.FifthRow02,PosY.FifthRow,SizeX.Key,SizeY.Key),
	Key_Y: new Button("Y",PosX.ThirdRow06,PosY.ThirdRow,SizeX.Key,SizeY.Key),
	Key_Z: new Button("Z",PosX.FifthRow01,PosY.FifthRow,SizeX.Key,SizeY.Key),
	// Key_LeftWin:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_RightWin:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_Apps:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_Sleep:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	Key_Numpad_0: new Button("0",PosX.EditRow3,PosY.SixthRow,SizeX.Double,SizeY.Key),
	Key_Numpad_1: new Button("1",PosX.EditRow3,PosY.FifthRow,SizeX.Key,SizeY.Key),
	Key_Numpad_2: new Button("2",PosX.EditRow4,PosY.FifthRow,SizeX.Key,SizeY.Key),
	Key_Numpad_3: new Button("3",PosX.EditRow5,PosY.FifthRow,SizeX.Key,SizeY.Key),
	Key_Numpad_4: new Button("4",PosX.EditRow3,PosY.FourthRow,SizeX.Key,SizeY.Key),
	Key_Numpad_5: new Button("5",PosX.EditRow4,PosY.FourthRow,SizeX.Key,SizeY.Key),
	Key_Numpad_6: new Button("6",PosX.EditRow5,PosY.FourthRow,SizeX.Key,SizeY.Key),
	Key_Numpad_7: new Button("7",PosX.EditRow3,PosY.ThirdRow,SizeX.Key,SizeY.Key),
	Key_Numpad_8: new Button("8",PosX.EditRow4,PosY.ThirdRow,SizeX.Key,SizeY.Key),
	Key_Numpad_9: new Button("9",PosX.EditRow5,PosY.ThirdRow,SizeX.Key,SizeY.Key),
	Key_Numpad_Multiply: new Button("*",PosX.EditRow5,PosY.SecondRow,SizeX.Key,SizeY.Key),
	Key_Numpad_Add: new Button("+",PosX.EditRow6,PosY.ThirdRow,SizeX.Key,SizeY.Double),
	Key_Numpad_Subtract: new Button("-",PosX.EditRow6,PosY.SecondRow,SizeX.Key,SizeY.Key),
	Key_Numpad_Decimal: new Button(".",PosX.EditRow5,PosY.SixthRow,SizeX.Key,SizeY.Key),
	// Key_Numpad_Comma: new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	Key_Numpad_Divide: new Button("/",PosX.EditRow4,PosY.SecondRow,SizeX.Key,SizeY.Key),
	Key_Numpad_Enter: new Button("Enter",PosX.EditRow6,PosY.FifthRow,SizeX.Key,SizeY.Double),
	Key_F1: new Button("F1",PosX.FirstRow01,PosY.FirstRow,SizeX.Key,SizeY.Key),
	Key_F2: new Button("F2",PosX.FirstRow02,PosY.FirstRow,SizeX.Key,SizeY.Key),
	Key_F3: new Button("F3",PosX.FirstRow03,PosY.FirstRow,SizeX.Key,SizeY.Key),
	Key_F4: new Button("F4",PosX.FirstRow04,PosY.FirstRow,SizeX.Key,SizeY.Key),
	Key_F5: new Button("F5",PosX.FirstRow05,PosY.FirstRow,SizeX.Key,SizeY.Key),
	Key_F6: new Button("F6",PosX.FirstRow06,PosY.FirstRow,SizeX.Key,SizeY.Key),
	Key_F7: new Button("F7",PosX.FirstRow07,PosY.FirstRow,SizeX.Key,SizeY.Key),
	Key_F8: new Button("F8",PosX.FirstRow08,PosY.FirstRow,SizeX.Key,SizeY.Key),
	Key_F9: new Button("F9",PosX.FirstRow09,PosY.FirstRow,SizeX.Key,SizeY.Key),
	Key_F10: new Button("F10",PosX.FirstRow10,PosY.FirstRow,SizeX.Key,SizeY.Key),
	Key_F11: new Button("F11",PosX.FirstRow11,PosY.FirstRow,SizeX.Key,SizeY.Key),
	Key_F12: new Button("F12",PosX.FirstRow12,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_F13:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_F14:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_F15:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_F16:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_F17:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_F18:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_F19:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_F20:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_F21:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_F22:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_F23:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_F24:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	Key_NumLock: new Button("Num\nLock",PosX.EditRow3,PosY.SecondRow,SizeX.Key,SizeY.Key),
	// Key_ScrollLock:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	Key_LeftShift: new Button("Shift",PosX.FifthRow00,PosY.FifthRow,SizeX.Shift,SizeY.Key),
	Key_RightShift: new Button("Shift",PosX.FifthRow11,PosY.FifthRow,SizeX.Shift,SizeY.Key),
	Key_LeftControl: new Button("Ctrl",PosX.SixthRow0,PosY.SixthRow,SizeX.Ctrl,SizeY.Key),
	Key_RightControl: new Button("Ctrl",PosX.SixthRow4,PosY.SixthRow,SizeX.Ctrl,SizeY.Key),
	Key_LeftAlt: new Button("Alt",PosX.SixthRow1,PosY.SixthRow,SizeX.Alt,SizeY.Key),
	Key_RightAlt: new Button("Alt",PosX.SixthRow3,PosY.SixthRow,SizeX.Alt,SizeY.Key),
	// Key_WebBack:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_WebForward:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_WebRefresh:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_WebStop:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_WebSearch:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_WebFavourites:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_WebHome:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_Mute:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_VolumeDown:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_VolumeUp:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_NextTrack:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_PrevTrack:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_MediaStop:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_Stop:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_PlayPause:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_Mail:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_MediaSelect:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	Key_SemiColon: new Button(";",PosX.FourthRow10,PosY.FourthRow,SizeX.Key,SizeY.Key),
	// Key_Plus: new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	Key_Equals: new Button("=",PosX.SecondRow12,PosY.SecondRow,SizeX.Key,SizeY.Key),
	Key_Comma: new Button(",",PosX.FifthRow08,PosY.FifthRow,SizeX.Key,SizeY.Key),
	Key_Minus: new Button("-",PosX.SecondRow11,PosY.SecondRow,SizeX.Key,SizeY.Key),
	Key_Period: new Button(".",PosX.FifthRow09,PosY.FifthRow,SizeX.Key,SizeY.Key),
	Key_Slash: new Button("/",PosX.FifthRow10,PosY.FifthRow,SizeX.Key,SizeY.Key),
	Key_Grave: new Button("~",PosX.SecondRow00,PosY.SecondRow,SizeX.Key,SizeY.Key),
	Key_LeftBracket: new Button("[",PosX.ThirdRow11,PosY.ThirdRow,SizeX.Key,SizeY.Key),
	Key_BackSlash: new Button("\\",PosX.ThirdRow13,PosY.ThirdRow,SizeX.Backslash,SizeY.Key),
	Key_RightBracket: new Button("]",PosX.ThirdRow12,PosY.ThirdRow,SizeX.Key,SizeY.Key),
	Key_Apostrophe: new Button("\"",PosX.FourthRow11,PosY.FourthRow,SizeX.Key,SizeY.Key),
	// Key_OEM_102:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_ä:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_ö:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_ü:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_ß:new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_Acute: new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_LessThan: new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_Circumflex: new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_Hash: new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_Colon: new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_ABNT_C1: new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_Yen: new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_ABNT_C2: new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_Numpad_Equals: new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_Underline: new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_AX: new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_Unlabeled: new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_Calculator: new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_AT: new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_Power: new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_Wake: new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_MyComputer: new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_GreenModifier: new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key),
	// Key_OrangeModifier: new Button("",PosX.FirstRow00,PosY.FirstRow,SizeX.Key,SizeY.Key)
};
type Action={
	readonly area: string,
	readonly category: string,
	readonly action: string;
};
const actions={
	UI_Up: {area: "General Controls",category: "Interface Mode",action: "UI Panel Up"},
	UI_Down: {area: "General Controls",category: "Interface Mode",action: "UI Panel Down"},
	UI_Left: {area: "General Controls",category: "Interface Mode",action: "UI Panel Left"},
	UI_Right: {area: "General Controls",category: "Interface Mode",action: "UI Panel Right"},
	UI_Select: {area: "General Controls",category: "Interface Mode",action: "UI Panel Select"},
	UI_Back: {area: "General Controls",category: "Interface Mode",action: "UI Panel Back"},
	UI_Toggle: {area: "General Controls",category: "Interface Mode",action: "UI Nested Toggle"},
	CycleNextPanel: {area: "General Controls",category: "Interface Mode",action: "Next Panel Tab"},
	CyclePreviousPanel: {area: "General Controls",category: "Interface Mode",action: "Previous Panel Tab"},
	CycleNextPage: {area: "General Controls",category: "Interface Mode",action: "Next Page"},
	CyclePreviousPage: {area: "General Controls",category: "Interface Mode",action: "Previous Page"},
	CamPitchAxis: {area: "General Controls",category: "Galaxy Map",action: "Galaxy Cam Pitch Axis"},
	CamPitchUp: {area: "General Controls",category: "Galaxy Map",action: "Galaxy Cam Pitch Up"},
	CamPitchDown: {area: "General Controls",category: "Galaxy Map",action: "Galaxy Cam Pitch Down"},
	CamYawAxis: {area: "General Controls",category: "Galaxy Map",action: "Galaxy Cam Yaw Axis"},
	CamYawLeft: {area: "General Controls",category: "Galaxy Map",action: "Galaxy Cam Yaw Left"},
	CamYawRight: {area: "General Controls",category: "Galaxy Map",action: "Galaxy Cam Yaw Right"},
	CamTranslateYAxis: {area: "General Controls",category: "Galaxy Map",action: "Galaxy Cam Translate Y-Axis"},
	CamTranslateForward: {area: "General Controls",category: "Galaxy Map",action: "Galaxy Cam Translate Forward"},
	CamTranslateBackward: {area: "General Controls",category: "Galaxy Map",action: "Galaxy Cam Translate Backward"},
	CamTranslateXAxis: {area: "General Controls",category: "Galaxy Map",action: "Galaxy Cam Translate X-Axis"},
	CamTranslateLeft: {area: "General Controls",category: "Galaxy Map",action: "Galaxy Cam Translate Left"},
	CamTranslateRight: {area: "General Controls",category: "Galaxy Map",action: "Galaxy Cam Translate Right"},
	CamTranslateZAxis: {area: "General Controls",category: "Galaxy Map",action: "Galaxy  Cam Translate Z-Axis"},
	CamTranslateUp: {area: "General Controls",category: "Galaxy Map",action: "Galaxy Cam Translate Up"},
	CamTranslateDown: {area: "General Controls",category: "Galaxy Map",action: "Galaxy Cam Translate Down"},
	CamZoomAxis: {area: "General Controls",category: "Galaxy Map",action: "Galaxy Cam Zoom Axis"},
	CamZoomIn: {area: "General Controls",category: "Galaxy Map",action: "Galaxy Cam Zoom In"},
	CamZoomOut: {area: "General Controls",category: "Galaxy Map",action: "Galaxy Cam Zoom Out"},
	CamTranslateZHold: {area: "General Controls",category: "Galaxy Map",action: "Galaxy Cam Set Y-Axis to Z-Axis"},
	GalaxyMapHome: {area: "General Controls",category: "Galaxy Map",action: "Galaxy Cam Select Current System"},
	PhotoCameraToggle: {area: "General Controls",category: "Camera Suite",action: "Ship - Toggle Camera Suite"},
	PhotoCameraToggle_Buggy: {area: "General Controls",category: "Camera Suite",action: "SRV - Toggle Camera Suite"},
	PhotoCameraToggle_Humanoid: {area: "General Controls",category: "Camera Suite",action: "Command - Toggle Camera Suite"},
	VanityCameraScrollLeft: {area: "General Controls",category: "Camera Suite",action: "Previous Camera"},
	VanityCameraScrollRight: {area: "General Controls",category: "Camera Suite",action: "Next Camera"},
	ToggleFreeCam: {area: "General Controls",category: "Camera Suite",action: "Enter Free Camera"},
	VanityCameraOne: {area: "General Controls",category: "Camera Suite",action: "Camera - Cockpit Front"},
	VanityCameraTwo: {area: "General Controls",category: "Camera Suite",action: "Camera - Cockpit Back"},
	VanityCameraThree: {area: "General Controls",category: "Camera Suite",action: "Camera - CMDR 1"},
	VanityCameraFour: {area: "General Controls",category: "Camera Suite",action: "Camera - CMDR 2"},
	VanityCameraFive: {area: "General Controls",category: "Camera Suite",action: "Camera - Co-Pilot 1"},
	VanityCameraSix: {area: "General Controls",category: "Camera Suite",action: "Camera - Co-Pilot 2"},
	VanityCameraSeven: {area: "General Controls",category: "Camera Suite",action: "Camera - Front"},
	VanityCameraEight: {area: "General Controls",category: "Camera Suite",action: "Camera - Back"},
	VanityCameraNine: {area: "General Controls",category: "Camera Suite",action: "Camera - Low"},
	FreeCamToggleHUD: {area: "General Controls",category: "Free Camera",action: "Toggle HUD"},
	FreeCamSpeedInc: {area: "General Controls",category: "Free Camera",action: "Increase Speed"},
	FreeCamSpeedDec: {area: "General Controls",category: "Free Camera",action: "Decrease Speed"},
	MoveFreeCamY: {area: "General Controls",category: "Free Camera",action: "Forward Axis"},
	ToggleReverseThrottleInputFreeCam: {area: "General Controls",category: "Free Camera",action: "Forward Only Throttle Reverse"},
	MoveFreeCamForward: {area: "General Controls",category: "Free Camera",action: "Move Forward"},
	MoveFreeCamBackwards: {area: "General Controls",category: "Free Camera",action: "Move Backward"},
	MoveFreeCamX: {area: "General Controls",category: "Free Camera",action: "Lateral Axis"},
	MoveFreeCamRight: {area: "General Controls",category: "Free Camera",action: "Move Right"},
	MoveFreeCamLeft: {area: "General Controls",category: "Free Camera",action: "Move Left"},
	MoveFreeCamZ: {area: "General Controls",category: "Free Camera",action: "Lift Axis"},
	MoveFreeCamUpAxis: {area: "General Controls",category: "Free Camera",action: "Move Up (Analogue)"},
	MoveFreeCamDownAxis: {area: "General Controls",category: "Free Camera",action: "Move Down (Analogue)"},
	MoveFreeCamUp: {area: "General Controls",category: "Free Camera",action: "Move Up"},
	MoveFreeCamDown: {area: "General Controls",category: "Free Camera",action: "Move Down"},
	PitchCamera: {area: "General Controls",category: "Free Camera",action: "Pitch Axis"},
	PitchCameraUp: {area: "General Controls",category: "Free Camera",action: "Pitch Up"},
	PitchCameraDown: {area: "General Controls",category: "Free Camera",action: "Pitch Down"},
	YawCamera: {area: "General Controls",category: "Free Camera",action: "Yaw Axis"},
	YawCameraLeft: {area: "General Controls",category: "Free Camera",action: "Yaw Left"},
	YawCameraRight: {area: "General Controls",category: "Free Camera",action: "Yaw Right"},
	RollCamera: {area: "General Controls",category: "Free Camera",action: "Roll Axis"},
	RollCameraLeft: {area: "General Controls",category: "Free Camera",action: "Roll Left"},
	RollCameraRight: {area: "General Controls",category: "Free Camera",action: "Roll Right"},
	ToggleRotationLock: {area: "General Controls",category: "Free Camera",action: "Stabiliser On/Off Toggle"},
	FixCameraRelativetoggle: {area: "General Controls",category: "Free Camera",action: "Camera / Ship Controls Toggle"},
	FixCameraWorldToggle: {area: "General Controls",category: "Free Camera",action: "Attach / Detach Camera"},
	QuitCamera: {area: "General Controls",category: "Free Camera",action: "Exit Free Camera"},
	ToggleAdvanceMode: {area: "General Controls",category: "Free Camera",action: "Zoom / Blur Toggle"},
	FreeCamZoomIn: {area: "General Controls",category: "Free Camera",action: "Increase Zoom/Focus"},
	FreeCamZoomOut: {area: "General Controls",category: "Free Camera",action: "Decrease Zoom/Focus"},
	FStopDec: {area: "General Controls",category: "Free Camera",action: "Decrease Blur"},
	FStopInc: {area: "General Controls",category: "Free Camera",action: "Increase Blur"},
	CommanderCreator_Undo: {area: "General Controls",category: "Holo-Me",action: "Undo"},
	CommanderCreator_Redo: {area: "General Controls",category: "Holo-Me",action: "Redo"},
	CommanderCreator_Rotation_MouseToggle: {area: "General Controls",category: "Holo-Me",action: "Toggle Mouse Rotation"},
	CommanderCreator_Rotation: {area: "General Controls",category: "Holo-Me",action: "Rotate Camera"},
	GalnetAudio_Play_Pause: {area: "General Controls",category: "Playlist",action: "Play / Pause"},
	GalnetAudio_SkipForward: {area: "General Controls",category: "Playlist",action: "Skip Forward"},
	GalnetAudio_SkipBackward: {area: "General Controls",category: "Playlist",action: "Skip Backward"},
	GalnetAudio_ClearQueue: {area: "General Controls",category: "Playlist",action: "Clear Queue"},
	StoreEnableRotation: {area: "General Controls",category: "Store Camera",action: "Hold to Rotate"},
	StorePitchCamera: {area: "General Controls",category: "Store Camera",action: "Pitch Axis"},
	StoreYawCamera: {area: "General Controls",category: "Store Camera",action: "Yaw Axis"},
	StoreCamZoomIn: {area: "General Controls",category: "Store Camera",action: "Store Camera Zoom In"},
	StoreCamZoomOut: {area: "General Controls",category: "Store Camera",action: "Store Camera Zoom Out"},
	StoreToggle: {area: "General Controls",category: "Store Camera",action: "Store Toggle"},
	MouseReset: {area: "Ship Controls",category: "Mouse Controls",action: "Reset Mouse"},
	YawAxisRaw: {area: "Ship Controls",category: "Flight Rotation",action: "Yaw Axis"},
	YawLeftButton: {area: "Ship Controls",category: "Flight Rotation",action: "Yaw Left"},
	YawRightButton: {area: "Ship Controls",category: "Flight Rotation",action: "Yaw Right"},
	YawtoRollButton: {area: "Ship Controls",category: "Flight Rotation",action: "Yaw Roll Button"},
	RollAxisRaw: {area: "Ship Controls",category: "Flight Rotation",action: "Roll Axis"},
	RollLeftButton: {area: "Ship Controls",category: "Flight Rotation",action: "Roll Left"},
	RollRightButton: {area: "Ship Controls",category: "Flight Rotation",action: "Roll Right"},
	PitchAxisRaw: {area: "Ship Controls",category: "Flight Rotation",action: "Pitch Axis"},
	PitchUpButton: {area: "Ship Controls",category: "Flight Rotation",action: "Pitch Up"},
	PitchDownButton: {area: "Ship Controls",category: "Flight Rotation",action: "Pitch Down"},
	LateralThrustRaw: {area: "Ship Controls",category: "Flight Thrust",action: "Lateral Thrust Axis"},
	LeftThrustButton: {area: "Ship Controls",category: "Flight Thrust",action: "Thrust Left"},
	RightThrustButton: {area: "Ship Controls",category: "Flight Thrust",action: "Thrust Right"},
	VerticalThrustRaw: {area: "Ship Controls",category: "Flight Thrust",action: "Vertical Thrust Axis"},
	UpThrustButton: {area: "Ship Controls",category: "Flight Thrust",action: "Thrust Up"},
	DownThrustButton: {area: "Ship Controls",category: "Flight Thrust",action: "Thrust Down"},
	AheadThrust: {area: "Ship Controls",category: "Flight Thrust",action: "Thrust Forward and Backward Axis"},
	ForwardThrustButton: {area: "Ship Controls",category: "Flight Thrust",action: "Thrust Forward"},
	BackwardThrustButton: {area: "Ship Controls",category: "Flight Thrust",action: "Thrust Backward"},
	UseAlternateFlightValuesToggle: {area: "Ship Controls",category: "Alternate Flight Controls",action: "Alternate Controls Toggle"},
	YawAxisAlternate: {area: "Ship Controls",category: "Alternate Flight Controls",action: "Yaw Axis"},
	RollAxisAlternate: {area: "Ship Controls",category: "Alternate Flight Controls",action: "Roll Axis"},
	PitchAxisAlternate: {area: "Ship Controls",category: "Alternate Flight Controls",action: "Pitch Axis"},
	LateralThrustAlternate: {area: "Ship Controls",category: "Alternate Flight Controls",action: "Lateral Thrust Axis"},
	VerticalThrustAlternate: {area: "Ship Controls",category: "Alternate Flight Controls",action: "Vertical Thrust Axis"},
	ThrottleAxis: {area: "Ship Controls",category: "Flight Throttle",action: "Throttle Axis"},
	ToggleReverseThrottleInput: {area: "Ship Controls",category: "Flight Throttle",action: "Forward Only Throttle Reverse"},
	ForwardKey: {area: "Ship Controls",category: "Flight Throttle",action: "Increase Throttle"},
	BackwardKey: {area: "Ship Controls",category: "Flight Throttle",action: "Decrease Throttle"},
	SetSpeedMinus100: {area: "Ship Controls",category: "Flight Throttle",action: "Set Speed to -100%"},
	SetSpeedMinus75: {area: "Ship Controls",category: "Flight Throttle",action: "Set Speed to -75%"},
	SetSpeedMinus50: {area: "Ship Controls",category: "Flight Throttle",action: "Set Speed to -50%"},
	SetSpeedMinus25: {area: "Ship Controls",category: "Flight Throttle",action: "Set Speed to -25%"},
	SetSpeedZero: {area: "Ship Controls",category: "Flight Throttle",action: "Set Speed to 0%"},
	SetSpeed25: {area: "Ship Controls",category: "Flight Throttle",action: "Set Speed to 25%"},
	SetSpeed50: {area: "Ship Controls",category: "Flight Throttle",action: "Set Speed to 50%"},
	SetSpeed75: {area: "Ship Controls",category: "Flight Throttle",action: "Set Speed to 75%"},
	SetSpeed100: {area: "Ship Controls",category: "Flight Throttle",action: "Set Speed to 100%"},
	YawAxis_Landing: {area: "Ship Controls",category: "Flight Landing Overrides",action: "Yaw Axis"},
	YawLeftButton_Landing: {area: "Ship Controls",category: "Flight Landing Overrides",action: "Yaw Left"},
	YawRightButton_Landing: {area: "Ship Controls",category: "Flight Landing Overrides",action: "Yar Right"},
	PitchAxis_Landing: {area: "Ship Controls",category: "Flight Landing Overrides",action: "Pitch Axis"},
	PitchUpButton_Landing: {area: "Ship Controls",category: "Flight Landing Overrides",action: "Pitch Up"},
	PitchDownButton_Landing: {area: "Ship Controls",category: "Flight Landing Overrides",action: "Pitch Down"},
	RollAxis_Landing: {area: "Ship Controls",category: "Flight Landing Overrides",action: "Roll Axis"},
	RollLeftButton_Landing: {area: "Ship Controls",category: "Flight Landing Overrides",action: "Roll Left"},
	RollRightButton_Landing: {area: "Ship Controls",category: "Flight Landing Overrides",action: "Roll Right"},
	LateralThrust_Landing: {area: "Ship Controls",category: "Flight Landing Overrides",action: "Lateral Thrust Axis"},
	LeftThrustButton_Landing: {area: "Ship Controls",category: "Flight Landing Overrides",action: "Thrust Left"},
	RightThrustButton_Landing: {area: "Ship Controls",category: "Flight Landing Overrides",action: "Thrust Right"},
	VerticalThrust_Landing: {area: "Ship Controls",category: "Flight Landing Overrides",action: "Verticle Thrust Axis"},
	UpThrustButton_Landing: {area: "Ship Controls",category: "Flight Landing Overrides",action: "Thrust Up"},
	DownThrustButton_Landing: {area: "Ship Controls",category: "Flight Landing Overrides",action: "Thrust Down"},
	AheadThrust_Landing: {area: "Ship Controls",category: "Flight Landing Overrides",action: "Thrust forward and Backward Axis"},
	ForwardThrustButton_Landing: {area: "Ship Controls",category: "Flight Landing Overrides",action: "Thrust Forward"},
	BackwardThrustButton_Landing: {area: "Ship Controls",category: "Flight Landing Overrides",action: "Thrust Backward"},
	ToggleFlightAssist: {area: "Ship Controls",category: "Flight Miscellaneous",action: "Toggle Flight Assist"},
	UseBoostJuice: {area: "Ship Controls",category: "Flight Miscellaneous",action: "Engine Boost"},
	HyperSuperCombination: {area: "Ship Controls",category: "Flight Miscellaneous",action: "Toggle Frame Shift Drive"},
	Supercruise: {area: "Ship Controls",category: "Flight Miscellaneous",action: "Supercruise"},
	Hyperspace: {area: "Ship Controls",category: "Flight Miscellaneous",action: "Hyperspace Jump"},
	DisableRotationCorrectToggle: {area: "Ship Controls",category: "Flight Miscellaneous",action: "Rotational Correction"},
	OrbitLinesToggle: {area: "Ship Controls",category: "Flight Miscellaneous",action: "Toggle Orbit Lines"},
	SelectTarget: {area: "Ship Controls",category: "Targeting",action: "Select Target Ahead"},
	CycleNextTarget: {area: "Ship Controls",category: "Targeting",action: "Cycle Next Target"},
	CyclePreviousTarget: {area: "Ship Controls",category: "Targeting",action: "Cycle Previous Ship"},
	SelectHighestThreat: {area: "Ship Controls",category: "Targeting",action: "Select Highest Threat"},
	CycleNextHostileTarget: {area: "Ship Controls",category: "Targeting",action: "Cycle Next Hostile Target"},
	CyclePreviousHostileTarget: {area: "Ship Controls",category: "Targeting",action: "Cycle Previous Hostile Ship"},
	TargetWingman0: {area: "Ship Controls",category: "Targeting",action: "Select Teammate 1"},
	TargetWingman1: {area: "Ship Controls",category: "Targeting",action: "Select Teammate 2"},
	TargetWingman2: {area: "Ship Controls",category: "Targeting",action: "Select Teammate 3"},
	SelectTargetsTarget: {area: "Ship Controls",category: "Targeting",action: "Select Teammates's Target"},
	WingNavLock: {area: "Ship Controls",category: "Targeting",action: "Teammate Nav-Lock"},
	CycleNextSubsystem: {area: "Ship Controls",category: "Targeting",action: "Cycle Next Subsystem"},
	CyclePreviousSubsystem: {area: "Ship Controls",category: "Targeting",action: "Cycle Previous Subsystem"},
	TargetNextRouteSystem: {area: "Ship Controls",category: "Targeting",action: "Target Next System In Route"},
	PrimaryFire: {area: "Ship Controls",category: "Weapons",action: "Primary Fire"},
	SecondaryFire: {area: "Ship Controls",category: "Weapons",action: "Secondary Fire"},
	CycleFireGroupNext: {area: "Ship Controls",category: "Weapons",action: "Cycle Next Fire Group"},
	CycleFireGroupPrevious: {area: "Ship Controls",category: "Weapons",action: "Cycle Previous Firgroup"},
	DeployHardpointToggle: {area: "Ship Controls",category: "Weapons",action: "Deploy Hardpoints"},
	ToggleButtonUpInput: {area: "Ship Controls",category: "Cooling",action: "Silent Running"},
	DeployHeatsink: {area: "Ship Controls",category: "Cooling",action: "Deploy Heatsink"},
	ShipSpotLightToggle: {area: "Ship Controls",category: "Miscellaneous",action: "Ship Lights"},
	RadarRangeAxis: {area: "Ship Controls",category: "Miscellaneous",action: "Sensor Zoom Axis"},
	RadarIncreaseRange: {area: "Ship Controls",category: "Miscellaneous",action: "Increase Sensor Zoom"},
	RadarDecreaseRange: {area: "Ship Controls",category: "Miscellaneous",action: "Decrease Sensor Zoom"},
	IncreaseEnginesPower: {area: "Ship Controls",category: "Miscellaneous",action: "Divert Power to Engines"},
	IncreaseWeaponsPower: {area: "Ship Controls",category: "Miscellaneous",action: "Divert Power to Weapons"},
	IncreaseSystemsPower: {area: "Ship Controls",category: "Miscellaneous",action: "Divert Power to System"},
	ResetPowerDistribution: {area: "Ship Controls",category: "Miscellaneous",action: "Balance Power Distribution"},
	HMDReset: {area: "Ship Controls",category: "Miscellaneous",action: "Reset HMD Orientation"},
	ToggleCargoScoop: {area: "Ship Controls",category: "Miscellaneous",action: "Cargo Scoop"},
	EjectAllCargo: {area: "Ship Controls",category: "Miscellaneous",action: "Jettison All Cargo"},
	LandingGearToggle: {area: "Ship Controls",category: "Miscellaneous",action: "Landing Gear"},
	MicrophoneMute: {area: "Ship Controls",category: "Miscellaneous",action: "Microphone Mute"},
	UseShieldCell: {area: "Ship Controls",category: "Miscellaneous",action: "Use Shield Cell"},
	FireChaffLauncher: {area: "Ship Controls",category: "Miscellaneous",action: "Use Chaff Launcher"},
	ChargeECM: {area: "Ship Controls",category: "Miscellaneous",action: "Charge Ecm"},
	WEaponColourToggle: {area: "Ship Controls",category: "Miscellaneous",action: "Weapon Color"},
	EngineColourToggle: {area: "Ship Controls",category: "Miscellaneous",action: "Engine Color"},
	NightVisionToggle: {area: "Ship Controls",category: "Miscellaneous",action: "Night Vision"},
	UIFocus: {area: "Ship Controls",category: "Mode Switches",action: "UI Focus"},
	FocusLeftPanel: {area: "Ship Controls",category: "Mode Switches",action: "External Panel"},
	FocusCommsPanel: {area: "Ship Controls",category: "Mode Switches",action: "Comms Panel"},
	QuickCommsPanel: {area: "Ship Controls",category: "Mode Switches",action: "Quick Comms"},
	FocusRadarPanel: {area: "Ship Controls",category: "Mode Switches",action: "Role Panel"},
	FocusRightPanel: {area: "Ship Controls",category: "Mode Switches",action: "Internal Panel"},
	GalaxyMapOpen: {area: "Ship Controls",category: "Mode Switches",action: "Open Galaxy Map"},
	SystemMapOpen: {area: "Ship Controls",category: "Mode Switches",action: "Open System Map"},
	ShowPGScoreSummaryInput: {area: "Ship Controls",category: "Mode Switches",action: "Show CQC Score Screen"},
	HeadlookToggle: {area: "Ship Controls",category: "Mode Switches",action: "Headlook"},
	Pause: {area: "Ship Controls",category: "Mode Switches",action: "Game Menu"},
	FriendsMenu: {area: "Ship Controls",category: "Mode Switches",action: "Friends Menu"},
	OpenCodexGoToDiscovery: {area: "Ship Controls",category: "Mode Switches",action: "Open Discovery"},
	PlayerHUDModeToggle: {area: "Ship Controls",category: "Mode Switches",action: "Switch Cockpit Mode"},
	ExplorationFSSEnter: {area: "Ship Controls",category: "Mode Switches",action: "Enter FSS Mode"},
	HeadLookReset: {area: "Ship Controls",category: "Headlook Mode",action: "Reset Headlook"},
	HeadLookPitchUp: {area: "Ship Controls",category: "Headlook Mode",action: "Look Up"},
	HeadLookPitchDown: {area: "Ship Controls",category: "Headlook Mode",action: "Look Down"},
	HeadLookPitchAxisRaw: {area: "Ship Controls",category: "Headlook Mode",action: "Look Up and Down Axis"},
	HeadLookYawLeft: {area: "Ship Controls",category: "Headlook Mode",action: "Look Left"},
	HeadLookYawRight: {area: "Ship Controls",category: "Headlook Mode",action: "Look Right"},
	HeadLookYawAxis: {area: "Ship Controls",category: "Headlook Mode",action: "Look Left and Right Axis"},
	MultiCrewToggleMode: {area: "Ship Controls",category: "Multi-crew",action: "Mode Toggle"},
	MultiCrewPrimaryFire: {area: "Ship Controls",category: "Multi-crew",action: "Primary Fire"},
	MultiCrewSEcondaryFire: {area: "Ship Controls",category: "Multi-crew",action: "Secondary Fire"},
	MultiCrewPrimaryUtilityFire: {area: "Ship Controls",category: "Multi-crew",action: "Primary Utility Fire"},
	MultiCrewSecondaryUtilityfire: {area: "Ship Controls",category: "Multi-crew",action: "Secondary Utility Fire"},
	MultiCrewThirdPersonYawAxisRaw: {area: "Ship Controls",category: "Multi-crew",action: "Third-Person Yaw Axis"},
	MultiCrewThirdPersonYawLeftButton: {area: "Ship Controls",category: "Multi-crew",action: "Third-Person Yaw Left"},
	MultiCrewThirdPersonYawRightButton: {area: "Ship Controls",category: "Multi-crew",action: "Third-Person Yaw Right"},
	MultiCrewThirdPersonPitchAxisRaw: {area: "Ship Controls",category: "Multi-crew",action: "Third-Person Pitch Axis"},
	MultiCrewThirdPersonPitchUpButton: {area: "Ship Controls",category: "Multi-crew",action: "Third-Person Pitch Up"},
	MultiCrewThirdPersonPitchDownButton: {area: "Ship Controls",category: "Multi-crew",action: "Third-Person Pitch Down"},
	MultiCrewThirdPersonFovAxisRaw: {area: "Ship Controls",category: "Multi-crew",action: "Third-Person Field of View Axis"},
	MultiCrewThirdPersonFovOutButton: {area: "Ship Controls",category: "Multi-crew",action: "Third-Person Field of View Out"},
	MultiCrewThirdPersonFovInButton: {area: "Ship Controls",category: "Multi-crew",action: "Third-Person Field of View In"},
	MultiCrewCockpitUICycleForward: {area: "Ship Controls",category: "Multi-crew",action: "Cycle Cockpit UI Forwards"},
	MultiCrewCockpitUICycleBackward: {area: "Ship Controls",category: "Multi-crew",action: "Cycle Cockpit UI Backwards"},
	OrderRequestDock: {area: "Ship Controls",category: "Fighter Orders",action: "Recall Fighter"},
	OrderDefensiveBehaviour: {area: "Ship Controls",category: "Fighter Orders",action: "Defend"},
	OrderAggressiveBehaviour: {area: "Ship Controls",category: "Fighter Orders",action: "Engage at Will"},
	OrderFocusTarget: {area: "Ship Controls",category: "Fighter Orders",action: "Attack Target"},
	OrderHoldFire: {area: "Ship Controls",category: "Fighter Orders",action: "Maintain formation"},
	OrderHoldPosition: {area: "Ship Controls",category: "Fighter Orders",action: "Hold Position"},
	OrderFollow: {area: "Ship Controls",category: "Fighter Orders",action: "Follow Me"},
	OpenOrders: {area: "Ship Controls",category: "Fighter Orders",action: "Open Orders"},
	ExplorationFSSCAmeraPitch: {area: "Ship Controls",category: "Full Spectrum System Scanner",action: "Camera Pitch"},
	ExplorationFSSCameraPitchIncreaseButton: {area: "Ship Controls",category: "Full Spectrum System Scanner",action: "Camera Pitch Increase"},
	ExplorationFSSCameraPitchDecreaseButton: {area: "Ship Controls",category: "Full Spectrum System Scanner",action: "Camera Pitch Decrease"},
	ExplorationFSSCameraYaw: {area: "Ship Controls",category: "Full Spectrum System Scanner",action: "Cameray Yaw"},
	ExplorationFSSCameraYawIncreaseButton: {area: "Ship Controls",category: "Full Spectrum System Scanner",action: "Camera Yaw Increase"},
	ExplorationFSSCameraYawDecreaseButton: {area: "Ship Controls",category: "Full Spectrum System Scanner",action: "Camera Yaw Decrease"},
	ExplorationFSSZoomIn: {area: "Ship Controls",category: "Full Spectrum System Scanner",action: "Zoom in to Target"},
	ExplorationFSSZoomOut: {area: "Ship Controls",category: "Full Spectrum System Scanner",action: "Zoom Out"},
	ExplorationFSSMiniZoomIn: {area: "Ship Controls",category: "Full Spectrum System Scanner",action: "Stepped Zoom In"},
	ExplorationFSSMiniZoomOut: {area: "Ship Controls",category: "Full Spectrum System Scanner",action: "Stepped Zoom Out"},
	ExplorationFSSRAdioTuningX_Raw: {area: "Ship Controls",category: "Full Spectrum System Scanner",action: "Tuning"},
	ExplorationFSSRadioTuningX_Increase: {area: "Ship Controls",category: "Full Spectrum System Scanner",action: "Tuning Right"},
	ExplorationFSSRadioTuningX_Decrease: {area: "Ship Controls",category: "Full Spectrum System Scanner",action: "Tuning Left"},
	ExplorationFSSRadioTuningAbsoluteX: {area: "Ship Controls",category: "Full Spectrum System Scanner",action: "Absolute Tuning"},
	ExplorationFSSDiscoveryScan: {area: "Ship Controls",category: "Full Spectrum System Scanner",action: "Discovery Scan"},
	ExplorationFSSQuit: {area: "Ship Controls",category: "Full Spectrum System Scanner",action: "Leave FSS"},
	ExplorationFSSTarget: {area: "Ship Controls",category: "Full Spectrum System Scanner",action: "Target Current Signal"},
	ExplorationFSSShowHelp: {area: "Ship Controls",category: "Full Spectrum System Scanner",action: "Show Help"},
	ExplorationSAAChangeScannedAreaViewToggle: {area: "Ship Controls",category: "Detailed Surface Scanner",action: "Toggle Front/Back View"},
	ExplorationSAAExitThirdPerson: {area: "Ship Controls",category: "Detailed Surface Scanner",action: "Exit Mode"},
	ExplorationSAANextGenus: {area: "Ship Controls",category: "Detailed Surface Scanner",action: "Next Filter"},
	ExplorationSAAPreviousGenus: {area: "Ship Controls",category: "Detailed Surface Scanner",action: "Previous Filter"},
	SAAThirdPersonYawAxisRaw: {area: "Ship Controls",category: "Detailed Surface Scanner",action: "Third-Person Yaw Axis"},
	SAAThirdPersonYawLeftButton: {area: "Ship Controls",category: "Detailed Surface Scanner",action: "Third-Person Yaw Left"},
	SAAThirdPersonYawRightButton: {area: "Ship Controls",category: "Detailed Surface Scanner",action: "Third-Person Yaw Right"},
	SAAThirdPersonPitchAxisRaw: {area: "Ship Controls",category: "Detailed Surface Scanner",action: "Third-Person Pitch Axis"},
	SAAThirdPersonPitchUpButton: {area: "Ship Controls",category: "Detailed Surface Scanner",action: "Third-Person Pitch Up"},
	SAAThirdPersonPitchDownButton: {area: "Ship Controls",category: "Detailed Surface Scanner",action: "Third-Person Pitch Down"},
	SAAThirdPersonFovAxisRaw: {area: "Ship Controls",category: "Detailed Surface Scanner",action: "Third-Person Field of View Axis"},
	SAAThirdPersonFovOutButton: {area: "Ship Controls",category: "Detailed Surface Scanner",action: "Third-Person Field of View Out"},
	SAAThirdPersonFovInButton: {area: "Ship Controls",category: "Detailed Surface Scanner",action: "Third-Person Field of View In"},
	ToggleDriveAssist: {area: "SRV Controls",category: "Driving",action: "Drive Assist"},
	SteeringAxis: {area: "SRV Controls",category: "Driving",action: "Steering Axis"},
	SteerLeftButton: {area: "SRV Controls",category: "Driving",action: "Steering Left Button"},
	SteerRightButton: {area: "SRV Controls",category: "Driving",action: "Steering Right Button"},
	BuggyRollAxisRaw: {area: "SRV Controls",category: "Driving",action: "Roll Axis"},
	BuggyRollLeftButton: {area: "SRV Controls",category: "Driving",action: "Roll Left Button"},
	BuggyRollRightButton: {area: "SRV Controls",category: "Driving",action: "Roll Right Button"},
	BuggyPitchAxis: {area: "SRV Controls",category: "Driving",action: "Pitch Axis"},
	BuggyPitchUpButton: {area: "SRV Controls",category: "Driving",action: "Pitch Up Button"},
	BuggyPitchDownButton: {area: "SRV Controls",category: "Driving",action: "Pitch Down Button"},
	VerticalThrustersButton: {area: "SRV Controls",category: "Driving",action: "Verticle Thrusters"},
	BuggyPrimaryFireButton: {area: "SRV Controls",category: "Driving",action: "SRV Primary Fire"},
	BuggySecondaryFireButton: {area: "SRV Controls",category: "Driving",action: "SRV Secondary Fire"},
	AutoBreakBuggyButton: {area: "SRV Controls",category: "Driving",action: "Handbrake"},
	HeadlightsBuggyButton: {area: "SRV Controls",category: "Driving",action: "Headlights"},
	ToggleBuggyTurretButton: {area: "SRV Controls",category: "Driving",action: "Toggle SRV Turret"},
	BuggyCycleFireGroupNext: {area: "SRV Controls",category: "Driving",action: "Cycle Next Fire Group"},
	BuggyCycleFireGroupPrevious: {area: "SRV Controls",category: "Driving",action: "Cycle Previous Fire Group"},
	SelectTarget_Buggy: {area: "SRV Controls",category: "Driving Targeting",action: "Select Target Ahead"},
	BuggyTurretYawAxisRaw: {area: "SRV Controls",category: "Driving Turret Controls",action: "SRV Turret Yaw Axis"},
	BuggyTurretYawLeftButton: {area: "SRV Controls",category: "Driving Turret Controls",action: "SRV Turret Yaw Left"},
	BuggyTurretYawRightButton: {area: "SRV Controls",category: "Driving Turret Controls",action: "SRV Turret Yaw Right"},
	BuggyTurretPitchAxisRaw: {area: "SRV Controls",category: "Driving Turret Controls",action: "SRV Turret Pitch Axis"},
	BuggyTurretPitchUpButton: {area: "SRV Controls",category: "Driving Turret Controls",action: "SRV Turret Pitch Up"},
	BuggyTurretPitchDownButton: {area: "SRV Controls",category: "Driving Turret Controls",action: "SRV Turret Pitch Down"},
	DriveSpeedAxis: {area: "SRV Controls",category: "Drive Throttle",action: "Drive Speed Axis"},
	BuggyToggleReverseThrottleInput: {area: "SRV Controls",category: "Drive Throttle",action: "Forward Only Throttle Reverse"},
	IncreaseSpeedButtonMax: {area: "SRV Controls",category: "Drive Throttle",action: "Accelerate Button"},
	DecreaseSpeedButtonMax: {area: "SRV Controls",category: "Drive Throttle",action: "Decelerate Button"},
	IncreaseSpeedButtonPartial: {area: "SRV Controls",category: "Drive Throttle",action: "Accelerate Axis"},
	DecreaseSpeedButtonPartial: {area: "SRV Controls",category: "Drive Throttle",action: "Decelerate Axis"},
	IncreaseEnginesPower_Buggy: {area: "SRV Controls",category: "Driving Miscellaneous",action: "Divert Power to Engines"},
	IncreaseWeaponsPower_Buggy: {area: "SRV Controls",category: "Driving Miscellaneous",action: "Divert Power to Weapons"},
	IncreaseSystemsPower_Buggy: {area: "SRV Controls",category: "Driving Miscellaneous",action: "Divert Power to System"},
	ResetPowerDistribution_Buggy: {area: "SRV Controls",category: "Driving Miscellaneous",action: "Balance Power Distribution"},
	ToggleCargoScoop_Buggy: {area: "SRV Controls",category: "Driving Miscellaneous",action: "Cargo Scoop"},
	EjectAllCargo_Buggy: {area: "SRV Controls",category: "Driving Miscellaneous",action: "Jettison All Cargo"},
	RecallDismissShip: {area: "SRV Controls",category: "Driving Miscellaneous",action: "Recall/Dismiss Ship"},
	UIFocus_Buggy: {area: "SRV Controls",category: "Driving Mode Switches",action: "UI Focus"},
	FocusLeftPanel_Buggy: {area: "SRV Controls",category: "Driving Mode Switches",action: "External Panel"},
	FocusCommsPanel_Buggy: {area: "SRV Controls",category: "Driving Mode Switches",action: "Comms Panel"},
	QuickCommsPanel_Buggy: {area: "SRV Controls",category: "Driving Mode Switches",action: "Quick Comms"},
	FocusRadarPanel_Buggy: {area: "SRV Controls",category: "Driving Mode Switches",action: "Role Panel"},
	FocusRightPanel_Buggy: {area: "SRV Controls",category: "Driving Mode Switches",action: "Internal Panel"},
	GalaxyMapOpen_Buggy: {area: "SRV Controls",category: "Driving Mode Switches",action: "Open Galaxy Map"},
	SystemMapOpen_Buggy: {area: "SRV Controls",category: "Driving Mode Switches",action: "Open System Map"},
	OpenCodexGoToDiscovery_Buggy: {area: "SRV Controls",category: "Driving Mode Switches",action: "Open Discovery"},
	PlayerHUDModeToggle_Buggy: {area: "SRV Controls",category: "Driving Mode Switches",action: "Switch Cockpit Mode"},
	HeadLookToggle_Buggy: {area: "SRV Controls",category: "Driving Mode Switches",action: "Headlook"},
	HumanoidForwardAxis: {area: "On Foot Controls",category: "On Foot",action: "Forward Axis"},
	HumanoidForwardButton: {area: "On Foot Controls",category: "On Foot",action: "Move Forward"},
	HumanoidBackwardButton: {area: "On Foot Controls",category: "On Foot",action: "Move Backward"},
	HumanoidStrafeAxis: {area: "On Foot Controls",category: "On Foot",action: "Strafe Axis"},
	HumanoidStrafeLeftButton: {area: "On Foot Controls",category: "On Foot",action: "Strafe Left"},
	HumanoidStrafeRightButton: {area: "On Foot Controls",category: "On Foot",action: "Strafe Right"},
	HumanoidRotateAxis: {area: "On Foot Controls",category: "On Foot",action: "Rotate Axis"},
	HumanoidRotateLeftButton: {area: "On Foot Controls",category: "On Foot",action: "Turn Left"},
	HumanoidRotateRightButton: {area: "On Foot Controls",category: "On Foot",action: "Turn Right"},
	HumanoidPitchAxis: {area: "On Foot Controls",category: "On Foot",action: "Pitch Axis"},
	HumanoidPitchUpButton: {area: "On Foot Controls",category: "On Foot",action: "Look Up"},
	HumanoidPitchDownButton: {area: "On Foot Controls",category: "On Foot",action: "Look Down"},
	HumanoidSprintButton: {area: "On Foot Controls",category: "On Foot",action: "Sprint"},
	HumanoidWalkButton: {area: "On Foot Controls",category: "On Foot",action: "Walk"},
	HumanoidCrouchButton: {area: "On Foot Controls",category: "On Foot",action: "Crouch"},
	HumanoidJumpButton: {area: "On Foot Controls",category: "On Foot",action: "Jump"},
	HumanoidPrimaryInteractButton: {area: "On Foot Controls",category: "On Foot",action: "Interact"},
	HumanoidSecondaryInteractButton: {area: "On Foot Controls",category: "On Foot",action: "Secondary Interact"},
	HumanoidItemWheelButton: {area: "On Foot Controls",category: "On Foot",action: "Open Item Wheel"},
	HumanoidItemWheelButton_XAxis: {area: "On Foot Controls",category: "On Foot",action: "Item Wheel Horizontal"},
	HumanoidItemWheelButton_XLeft: {area: "On Foot Controls",category: "On Foot",action: "Item Wheel Left"},
	HumanoidItemWheelButton_XRight: {area: "On Foot Controls",category: "On Foot",action: "Item Wheel Right"},
	HumanoidItemWheelButton_YAxis: {area: "On Foot Controls",category: "On Foot",action: "Item Wheel Vertical"},
	HumanoidItemWheelButton_YUp: {area: "On Foot Controls",category: "On Foot",action: "Item Wheel Up"},
	HumanoidItemWheelButton_YDown: {area: "On Foot Controls",category: "On Foot",action: "Item Wheel Down"},
	HumanoidPrimaryFireButton: {area: "On Foot Controls",category: "On Foot",action: "Fire Weapon/Use Tool"},
	HumanoidZoomButton: {area: "On Foot Controls",category: "On Foot",action: "Aim Down Sights"},
	HumanoidThrowGrenadeButton: {area: "On Foot Controls",category: "On Foot",action: "Throw Grenade"},
	HumanoidMeleeButton: {area: "On Foot Controls",category: "On Foot",action: "Melee Attack"},
	HumanoidReloadButton: {area: "On Foot Controls",category: "On Foot",action: "Reload"},
	HumanoidSwitchWeapon: {area: "On Foot Controls",category: "On Foot",action: "Switch Weapon"},
	HumanoidSelectPrimaryWeaponButton: {area: "On Foot Controls",category: "On Foot",action: "Select Primary Weapon"},
	HumanoidSelectSecondaryWeaponButton: {area: "On Foot Controls",category: "On Foot",action: "Select Secondary Weapon"},
	HumanoidSelectUtilityWeaponButton: {area: "On Foot Controls",category: "On Foot",action: "Select Tool"},
	HumanoidSelectNextWeaponButton: {area: "On Foot Controls",category: "On Foot",action: "Select Next Weapon"},
	HumanoidSelectPreviousWeaponButton: {area: "On Foot Controls",category: "On Foot",action: "Select Previous Weapon"},
	HumanoidHideWeaponButton: {area: "On Foot Controls",category: "On Foot",action: "Holster Weapon"},
	HumanoidSelectNextGrenadeTypeButton: {area: "On Foot Controls",category: "On Foot",action: "Select Next Grenade Type"},
	HumanoidSelectPreviousGrenadeTypeButton: {area: "On Foot Controls",category: "On Foot",action: "Select Previous Grenade Type"},
	HumanoidToggleFlashlightButton: {area: "On Foot Controls",category: "On Foot",action: "Toggle Flashlight"},
	HumanoidToggleNightVisionButton: {area: "On Foot Controls",category: "On Foot",action: "Toggle Night Vision"},
	HumanoidToggleShieldsButton: {area: "On Foot Controls",category: "On Foot",action: "Toggle Shields"},
	HumanoidClearAuthorityLevel: {area: "On Foot Controls",category: "On Foot",action: "Clear Authority Level"},
	HumanoidHealthPack: {area: "On Foot Controls",category: "On Foot",action: "Use Health Pack"},
	HumanoidBattery: {area: "On Foot Controls",category: "On Foot",action: "Use Engergy Cell"},
	HumanoidSelectFragGrenade: {area: "On Foot Controls",category: "On Foot",action: "Select Frag Grenade"},
	HumanoidSelectEMPGrenade: {area: "On Foot Controls",category: "On Foot",action: "Select EMP Grenade"},
	HumanoidSelectShieldGrenade: {area: "On Foot Controls",category: "On Foot",action: "Select Shield Grenade"},
	HumanoidSwitchToRechargeTool: {area: "On Foot Controls",category: "On Foot",action: "Select Energylink"},
	HumanoidSwitchToCompAnalyser: {area: "On Foot Controls",category: "On Foot",action: "Select Profile Analyser"},
	HumanoidSwitchToSuitTool: {area: "On Foot Controls",category: "On Foot",action: "Select Suit Specific Tool"},
	HumanoidToggleToolModeButton: {area: "On Foot Controls",category: "On Foot",action: "Toggle Tool Mode"},
	HumanoidToggleMissionHelpPanelButton: {area: "On Foot Controls",category: "On Foot",action: "Toggle Help"},
	GalaxyMapOpen_Humanoid: {area: "On Foot Controls",category: "On Foot Mode Switches",action: "Open Galaxy Map"},
	SystemMapOpen_Humanoid: {area: "On Foot Controls",category: "On Foot Mode Switches",action: "Open System Map"},
	FocusCommsPanel_Humanoid: {area: "On Foot Controls",category: "On Foot Mode Switches",action: "Comms Panel"},
	QuickCommsPanel_Humanoid: {area: "On Foot Controls",category: "On Foot Mode Switches",action: "Quick Comms"},
	HumanoidOpenAccessPanelButton: {area: "On Foot Controls",category: "On Foot Mode Switches",action: "Open Insight Hub"},
	HumanoidConflictContextualUIButton: {area: "On Foot Controls",category: "On Foot Mode Switches",action: "Open Conflict Zone Battle Stats"}
} as const;